# Generated by Django 6.0.3 on 2026-03-16 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0003_category_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='correct_count',
            field=models.IntegerField(default=0, verbose_name='Правильных ответов'),
        ),
        migrations.AddField(
            model_name='entry',
            name='wrong_count',
            field=models.IntegerField(default=0, verbose_name='Неправильных ответов'),
        ),
    ]
